# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d2b7dfc142892008b20c973a2b118d2c055bd70abf5284fd633f3d8d7fa8817eef56282ed2bfffc27c717f4a8618959592ae3edb9bceb08f34a0576096713b

test:
  secret_key_base: c878231bddb3ac3011244dd94d2ad2553ed34e45903c5d53a099763682712967c5b95bb7f96e66f116d400af6710ead141b34998d1e9b7acec7950f1109bc71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
